# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'clipboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(760, 350)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(310, 40, 121, 20))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setGeometry(QtCore.QRect(120, 40, 500, 250))  # 增大宽度以容纳按钮
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")

        # 创建滚动区域的内容部件
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")

        # 使用垂直布局来放置每条记录
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")

        # 添加标题标签
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)

        # 添加一个示例记录（实际使用时应该动态添加）
        self.add_sample_record()

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def add_sample_record(self):
        """添加一个示例记录，展示每条记录的布局"""
        record_widget = QtWidgets.QWidget()
        record_layout = QtWidgets.QHBoxLayout(record_widget)
        record_layout.setContentsMargins(0, 0, 0, 0)

        # 文本标签
        text_label = QtWidgets.QLabel("示例文本内容")
        text_label.setWordWrap(True)
        text_label.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        record_layout.addWidget(text_label)

        # 复制按钮
        copy_btn = QtWidgets.QPushButton("复制")
        copy_btn.setFixedSize(60, 30)
        record_layout.addWidget(copy_btn)

        # 删除按钮
        delete_btn = QtWidgets.QPushButton("删除")
        delete_btn.setFixedSize(60, 30)
        record_layout.addWidget(delete_btn)

        self.verticalLayout.addWidget(record_widget)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "剪切板历史"))


